from .login_view import *
from .profile_view import *
from .register_view import *
from .fav_view import *
from .profile_edit import *
from .account_url_view import *
from .profile_wallet_view import *
from .edit_location_view import *
from .profile_ads_view import *